# -*- coding:utf-8 -*-

print("hello world\n")
print("hello world2\n")
print("hello world3\n")
print("hello world4\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
print("hello world5\n")
